# ============
# Server 配置
# ============
server:
  port: 8001
  servlet:
    context-path: /resume/web

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 10000